@startuml
title CU-02 · Registrarse
skinparam maxMessageSize 160
autonumber

actor Ciudadano
boundary "Vista 01 Login\n(LoginScreen)" as V1
boundary "Vista 07 Registro\n(RegisterScreen)" as V7
participant "ServicioCuenta" as SvcCuenta
database "LocalStore\n(cuentas.json)" as DB

group Flujo Principal y Escenarios alternativos
    Ciudadano -> V1: clic en "Registrarse"
    V1 -> V7: Get.toNamed(/register)
    Ciudadano -> V7: Ingresa nombres, apellidos, DNI, telefono,\ncorreo, usuario y contrasena
    Ciudadano -> V7: clic "Registrarse"
    V7 -> V7: valida que todos los campos no esten vacios
    V7 -> SvcCuenta: crearCuenta(CrearCuentaRequest)
    SvcCuenta -> DB: busca cuenta con mismo usuario\no mismo correo
    DB --> SvcCuenta: coincidencias

    alt Datos validos y unicos
        SvcCuenta -> DB: agrega CuentaResponse\n(tipoCuenta = CIUDADANO · id autoincrement)
        DB --> SvcCuenta: cuenta creada
        SvcCuenta --> V7: exito
        V7 -> V7: AppToast.success\nGet.offAllNamed(/login)
        V7 --> Ciudadano: Redirige a Vista 01 Login
    else Datos invalidos o incompletos (Escenario 1)
        V7 --> Ciudadano: AppToast.error "Completa todos los campos"
    else Usuario o correo ya registrado (Escenario 2)
        SvcCuenta --> V7: Exception con el motivo
        V7 --> Ciudadano: AppToast.error con el motivo
    end
end
@enduml
